/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const OccasionCategory = IDL.Variant({
  'work' : IDL.Null,
  'festive' : IDL.Null,
  'casual' : IDL.Null,
  'special' : IDL.Null,
  'formal' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StylePreference = IDL.Variant({
  'western' : IDL.Null,
  'indian' : IDL.Null,
  'indoWestern' : IDL.Null,
});
export const Occasion = IDL.Record({
  'category' : OccasionCategory,
  'subOccasion' : IDL.Text,
});
export const EditableUserProfile = IDL.Record({
  'jewellery' : IDL.Vec(IDL.Text),
  'stylePreference' : StylePreference,
  'accessories' : IDL.Vec(IDL.Text),
  'skinTone' : IDL.Text,
  'occasion' : Occasion,
  'bodyType' : IDL.Text,
  'outfits' : IDL.Vec(IDL.Text),
});
export const EditableOutfitRecommendation = IDL.Record({
  'jewellery' : IDL.Vec(IDL.Text),
  'outfitName' : IDL.Text,
  'description' : IDL.Text,
  'colorPalette' : IDL.Vec(IDL.Text),
  'styleTips' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSubOccasion' : IDL.Func([IDL.Text, OccasionCategory], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAccessories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllFestiveSubOccasions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(EditableUserProfile)], ['query']),
  'getAllProfilesByBodyTypes' : IDL.Func(
      [],
      [IDL.Vec(EditableUserProfile)],
      ['query'],
    ),
  'getCallerRecommendations' : IDL.Func(
      [],
      [IDL.Vec(EditableOutfitRecommendation)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(EditableUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getJewellery' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getOutfits' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRecommendationsForOccasion' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EditableOutfitRecommendation)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(EditableUserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'setAccessories' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'setFavorites' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'setJewellery' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'setOutfits' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateProfile' : IDL.Func([EditableUserProfile], [], []),
  'upsertProfile' : IDL.Func([EditableUserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const OccasionCategory = IDL.Variant({
    'work' : IDL.Null,
    'festive' : IDL.Null,
    'casual' : IDL.Null,
    'special' : IDL.Null,
    'formal' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StylePreference = IDL.Variant({
    'western' : IDL.Null,
    'indian' : IDL.Null,
    'indoWestern' : IDL.Null,
  });
  const Occasion = IDL.Record({
    'category' : OccasionCategory,
    'subOccasion' : IDL.Text,
  });
  const EditableUserProfile = IDL.Record({
    'jewellery' : IDL.Vec(IDL.Text),
    'stylePreference' : StylePreference,
    'accessories' : IDL.Vec(IDL.Text),
    'skinTone' : IDL.Text,
    'occasion' : Occasion,
    'bodyType' : IDL.Text,
    'outfits' : IDL.Vec(IDL.Text),
  });
  const EditableOutfitRecommendation = IDL.Record({
    'jewellery' : IDL.Vec(IDL.Text),
    'outfitName' : IDL.Text,
    'description' : IDL.Text,
    'colorPalette' : IDL.Vec(IDL.Text),
    'styleTips' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSubOccasion' : IDL.Func([IDL.Text, OccasionCategory], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAccessories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllFestiveSubOccasions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(EditableUserProfile)], ['query']),
    'getAllProfilesByBodyTypes' : IDL.Func(
        [],
        [IDL.Vec(EditableUserProfile)],
        ['query'],
      ),
    'getCallerRecommendations' : IDL.Func(
        [],
        [IDL.Vec(EditableOutfitRecommendation)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(EditableUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getJewellery' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getOutfits' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRecommendationsForOccasion' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EditableOutfitRecommendation)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(EditableUserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'setAccessories' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'setFavorites' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'setJewellery' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'setOutfits' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateProfile' : IDL.Func([EditableUserProfile], [], []),
    'upsertProfile' : IDL.Func([EditableUserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };