/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EditableOutfitRecommendation {
  'jewellery' : Array<string>,
  'outfitName' : string,
  'description' : string,
  'colorPalette' : Array<string>,
  'styleTips' : string,
}
export interface EditableUserProfile {
  'jewellery' : Array<string>,
  'stylePreference' : StylePreference,
  'accessories' : Array<string>,
  'skinTone' : string,
  'occasion' : Occasion,
  'bodyType' : string,
  'outfits' : Array<string>,
}
export interface Occasion {
  'category' : OccasionCategory,
  'subOccasion' : string,
}
export type OccasionCategory = { 'work' : null } |
  { 'festive' : null } |
  { 'casual' : null } |
  { 'special' : null } |
  { 'formal' : null };
export type StylePreference = { 'western' : null } |
  { 'indian' : null } |
  { 'indoWestern' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSubOccasion' : ActorMethod<[string, OccasionCategory], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAccessories' : ActorMethod<[], Array<string>>,
  'getAllFestiveSubOccasions' : ActorMethod<[], Array<string>>,
  'getAllProfiles' : ActorMethod<[], Array<EditableUserProfile>>,
  'getAllProfilesByBodyTypes' : ActorMethod<[], Array<EditableUserProfile>>,
  'getCallerRecommendations' : ActorMethod<
    [],
    Array<EditableOutfitRecommendation>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [EditableUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavorites' : ActorMethod<[], Array<string>>,
  'getJewellery' : ActorMethod<[], Array<string>>,
  'getOutfits' : ActorMethod<[], Array<string>>,
  'getRecommendationsForOccasion' : ActorMethod<
    [string],
    Array<EditableOutfitRecommendation>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [EditableUserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'setAccessories' : ActorMethod<[Array<string>], undefined>,
  'setFavorites' : ActorMethod<[Array<string>], undefined>,
  'setJewellery' : ActorMethod<[Array<string>], undefined>,
  'setOutfits' : ActorMethod<[Array<string>], undefined>,
  'updateProfile' : ActorMethod<[EditableUserProfile], undefined>,
  'upsertProfile' : ActorMethod<[EditableUserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];