/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EditableUserProfile {
    jewellery: Array<string>;
    stylePreference: StylePreference;
    accessories: Array<string>;
    skinTone: string;
    occasion: Occasion;
    bodyType: string;
    outfits: Array<string>;
}
export interface Occasion {
    category: OccasionCategory;
    subOccasion: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface EditableOutfitRecommendation {
    jewellery: Array<string>;
    outfitName: string;
    description: string;
    colorPalette: Array<string>;
    styleTips: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum OccasionCategory {
    work = "work",
    festive = "festive",
    casual = "casual",
    special = "special",
    formal = "formal"
}
export enum StylePreference {
    western = "western",
    indian = "indian",
    indoWestern = "indoWestern"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addSubOccasion(name: string, category: OccasionCategory): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAccessories(): Promise<Array<string>>;
    getAllFestiveSubOccasions(): Promise<Array<string>>;
    getAllProfiles(): Promise<Array<EditableUserProfile>>;
    getAllProfilesByBodyTypes(): Promise<Array<EditableUserProfile>>;
    getCallerRecommendations(): Promise<Array<EditableOutfitRecommendation>>;
    getCallerUserProfile(): Promise<EditableUserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFavorites(): Promise<Array<string>>;
    getJewellery(): Promise<Array<string>>;
    getOutfits(): Promise<Array<string>>;
    getRecommendationsForOccasion(subOccasion: string): Promise<Array<EditableOutfitRecommendation>>;
    getUserProfile(user: Principal): Promise<EditableUserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    setAccessories(newAccessories: Array<string>): Promise<void>;
    setFavorites(newFavorites: Array<string>): Promise<void>;
    setJewellery(newJewellery: Array<string>): Promise<void>;
    setOutfits(newOutfits: Array<string>): Promise<void>;
    updateProfile(profile: EditableUserProfile): Promise<void>;
    upsertProfile(profile: EditableUserProfile): Promise<void>;
}
import type { EditableUserProfile as _EditableUserProfile, Occasion as _Occasion, OccasionCategory as _OccasionCategory, StylePreference as _StylePreference, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addSubOccasion(arg0: string, arg1: OccasionCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubOccasion(arg0, to_candid_OccasionCategory_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubOccasion(arg0, to_candid_OccasionCategory_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAccessories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccessories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccessories();
            return result;
        }
    }
    async getAllFestiveSubOccasions(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFestiveSubOccasions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFestiveSubOccasions();
            return result;
        }
    }
    async getAllProfiles(): Promise<Array<EditableUserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProfilesByBodyTypes(): Promise<Array<EditableUserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfilesByBodyTypes();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfilesByBodyTypes();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerRecommendations(): Promise<Array<EditableOutfitRecommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRecommendations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRecommendations();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<EditableUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFavorites(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavorites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavorites();
            return result;
        }
    }
    async getJewellery(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJewellery();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJewellery();
            return result;
        }
    }
    async getOutfits(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOutfits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOutfits();
            return result;
        }
    }
    async getRecommendationsForOccasion(arg0: string): Promise<Array<EditableOutfitRecommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendationsForOccasion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendationsForOccasion(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<EditableUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async setAccessories(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAccessories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAccessories(arg0);
            return result;
        }
    }
    async setFavorites(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFavorites(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFavorites(arg0);
            return result;
        }
    }
    async setJewellery(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setJewellery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setJewellery(arg0);
            return result;
        }
    }
    async setOutfits(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOutfits(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOutfits(arg0);
            return result;
        }
    }
    async updateProfile(arg0: EditableUserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_EditableUserProfile_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_EditableUserProfile_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async upsertProfile(arg0: EditableUserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertProfile(to_candid_EditableUserProfile_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertProfile(to_candid_EditableUserProfile_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_EditableUserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EditableUserProfile): EditableUserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_OccasionCategory_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OccasionCategory): OccasionCategory {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Occasion_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Occasion): Occasion {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_StylePreference_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StylePreference): StylePreference {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EditableUserProfile]): EditableUserProfile | null {
    return value.length === 0 ? null : from_candid_EditableUserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jewellery: Array<string>;
    stylePreference: _StylePreference;
    accessories: Array<string>;
    skinTone: string;
    occasion: _Occasion;
    bodyType: string;
    outfits: Array<string>;
}): {
    jewellery: Array<string>;
    stylePreference: StylePreference;
    accessories: Array<string>;
    skinTone: string;
    occasion: Occasion;
    bodyType: string;
    outfits: Array<string>;
} {
    return {
        jewellery: value.jewellery,
        stylePreference: from_candid_StylePreference_n15(_uploadFile, _downloadFile, value.stylePreference),
        accessories: value.accessories,
        skinTone: value.skinTone,
        occasion: from_candid_Occasion_n17(_uploadFile, _downloadFile, value.occasion),
        bodyType: value.bodyType,
        outfits: value.outfits
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    category: _OccasionCategory;
    subOccasion: string;
}): {
    category: OccasionCategory;
    subOccasion: string;
} {
    return {
        category: from_candid_OccasionCategory_n19(_uploadFile, _downloadFile, value.category),
        subOccasion: value.subOccasion
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    western: null;
} | {
    indian: null;
} | {
    indoWestern: null;
}): StylePreference {
    return "western" in value ? StylePreference.western : "indian" in value ? StylePreference.indian : "indoWestern" in value ? StylePreference.indoWestern : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    work: null;
} | {
    festive: null;
} | {
    casual: null;
} | {
    special: null;
} | {
    formal: null;
}): OccasionCategory {
    return "work" in value ? OccasionCategory.work : "festive" in value ? OccasionCategory.festive : "casual" in value ? OccasionCategory.casual : "special" in value ? OccasionCategory.special : "formal" in value ? OccasionCategory.formal : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EditableUserProfile>): Array<EditableUserProfile> {
    return value.map((x)=>from_candid_EditableUserProfile_n13(_uploadFile, _downloadFile, x));
}
function to_candid_EditableUserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EditableUserProfile): _EditableUserProfile {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_OccasionCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OccasionCategory): _OccasionCategory {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Occasion_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Occasion): _Occasion {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_StylePreference_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StylePreference): _StylePreference {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jewellery: Array<string>;
    stylePreference: StylePreference;
    accessories: Array<string>;
    skinTone: string;
    occasion: Occasion;
    bodyType: string;
    outfits: Array<string>;
}): {
    jewellery: Array<string>;
    stylePreference: _StylePreference;
    accessories: Array<string>;
    skinTone: string;
    occasion: _Occasion;
    bodyType: string;
    outfits: Array<string>;
} {
    return {
        jewellery: value.jewellery,
        stylePreference: to_candid_StylePreference_n26(_uploadFile, _downloadFile, value.stylePreference),
        accessories: value.accessories,
        skinTone: value.skinTone,
        occasion: to_candid_Occasion_n28(_uploadFile, _downloadFile, value.occasion),
        bodyType: value.bodyType,
        outfits: value.outfits
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    category: OccasionCategory;
    subOccasion: string;
}): {
    category: _OccasionCategory;
    subOccasion: string;
} {
    return {
        category: to_candid_OccasionCategory_n8(_uploadFile, _downloadFile, value.category),
        subOccasion: value.subOccasion
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StylePreference): {
    western: null;
} | {
    indian: null;
} | {
    indoWestern: null;
} {
    return value == StylePreference.western ? {
        western: null
    } : value == StylePreference.indian ? {
        indian: null
    } : value == StylePreference.indoWestern ? {
        indoWestern: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OccasionCategory): {
    work: null;
} | {
    festive: null;
} | {
    casual: null;
} | {
    special: null;
} | {
    formal: null;
} {
    return value == OccasionCategory.work ? {
        work: null
    } : value == OccasionCategory.festive ? {
        festive: null
    } : value == OccasionCategory.casual ? {
        casual: null
    } : value == OccasionCategory.special ? {
        special: null
    } : value == OccasionCategory.formal ? {
        formal: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
